# Basic Information 
title: José Ángel Vicente Gómez
position: Head of Health Economics
affiliation: Germans Trias i Pujol Hospital | University of Oxford | University of Barcelona | Universitat Pompeu Fabra
email: joseangel.vicgom@gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: José Ángel Vicente Gómez, health economics, policy evaluation, labor economics, public health
description: José Ángel Vicente Gómez is a health economist working in the field of policy evaluation.


theme: jekyll-theme-minimal
show_downloads: "true"

plugins:
  - jekyll-seo-tag
